import turtle 

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("grey")
tortuga.penup()
tortuga.goto((-500,0))
tortuga.pendown()
tortuga.right(70)
tortuga.forward(122)
tortuga.right(-140)
tortuga.forward(122)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("pink")
tortuga.penup()
tortuga.goto((-420, -120))
tortuga.pendown()
tortuga.left(70)
tortuga.forward(122)
tortuga.right(140)
tortuga.forward(122)
tortuga.left(180)
tortuga.forward(50)
tortuga.left(70)
tortuga.forward(50)
tortuga.left(180)
tortuga.forward(50)
tortuga.right(70)
tortuga.forward(50)
tortuga.left(70)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("purple")
tortuga.penup()
tortuga.goto((-300,0))
tortuga.pendown()
tortuga.right(90)
tortuga.forward(122)
tortuga.left(90)
tortuga.forward(70)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("blue")
tortuga.penup()
tortuga.goto((-122,0))
tortuga.pendown()
tortuga.left(180)
tortuga.forward(70)
tortuga.left(90)
tortuga.forward(60)
tortuga.left(90)
tortuga.forward(40)
tortuga.left(180)
tortuga.forward(40)
tortuga.left(90)
tortuga.forward(60)
tortuga.left(90)
tortuga.forward(70)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("green")
tortuga.penup()
tortuga.goto((-85,-120))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(122)
tortuga.right(150)
tortuga.forward(140)
tortuga.left(150)
tortuga.forward(122)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("yellow")
tortuga.penup()
tortuga.goto(20,0)
tortuga.pendown()
tortuga.left(0)
tortuga.forward(100)
tortuga.left(180)
tortuga.forward(50)
tortuga.left(90)
tortuga.forward(122)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("orange")
tortuga.penup()
tortuga.goto(160,0)
tortuga.pendown()
tortuga.left(270)
tortuga.forward(122)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("red")
tortuga.penup()
tortuga.goto((195,-120))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(122)
tortuga.right(150)
tortuga.forward(140)
tortuga.left(150)
tortuga.forward(122)

tortuga=turtle.Turtle()
tortuga.shape('turtle')
tortuga.pensize(15)
tortuga.color("black")
tortuga.penup()
tortuga.goto((300, -120))
tortuga.pendown()
tortuga.left(70)
tortuga.forward(122)
tortuga.right(140)
tortuga.forward(122)
tortuga.left(180)
tortuga.forward(50)
tortuga.left(70)
tortuga.forward(50)
tortuga.left(180)
tortuga.forward(50)
tortuga.right(70)
tortuga.forward(50)
tortuga.left(70)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(5)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((460, -120))
tortuga.pendown()
tortuga.right(0)
tortuga.forward(70)
tortuga.left(60)
tortuga.forward(70)
tortuga.left(70)
tortuga.forward(70)
tortuga.left(50)
tortuga.forward(60)
tortuga.left(50)
tortuga.forward(70)
tortuga.left(75)
tortuga.forward(73)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(5)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((564, -61))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(120)
tortuga.left(145)
tortuga.forward(75)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(2)
tortuga.color("pink")
tortuga.penup()
tortuga.goto((555,-43))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(70)
tortuga.left(145)
tortuga.forward(45)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(5)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((416, -61))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(120)
tortuga.right(145)
tortuga.forward(75)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(2)
tortuga.color("pink")
tortuga.penup()
tortuga.goto((425,-43))
tortuga.pendown()
tortuga.left(90)
tortuga.forward(70)
tortuga.right(145)
tortuga.forward(45)

tortuga=turtle.Turtle()
tortuga.shape('circle')
tortuga.pensize(15)
tortuga.color("olive")
tortuga.penup()
tortuga.goto((470, -50))
tortuga.pendown()

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(1)
tortuga.color("black")
tortuga.penup()
tortuga.goto((470, -46))
tortuga.pendown()
tortuga.left(90)

tortuga=turtle.Turtle()
tortuga.shape('circle')
tortuga.pensize(15)
tortuga.color("olive")
tortuga.penup()
tortuga.goto((510, -50))
tortuga.pendown()

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(1)
tortuga.color("black")
tortuga.penup()
tortuga.goto((510, -46))
tortuga.pendown()
tortuga.left(90)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(15)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((490, -78))
tortuga.pendown()
tortuga.right(90)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(3)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((400, -78))
tortuga.pendown()
tortuga.right(0)
tortuga.forward(60)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(3)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((400, -93))
tortuga.pendown()
tortuga.right(0)
tortuga.forward(65)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(3)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((580, -78))
tortuga.pendown()
tortuga.left(180)
tortuga.forward(60)

tortuga=turtle.Turtle()
tortuga.shape('classic')
tortuga.pensize(3)
tortuga.color("brown")
tortuga.penup()
tortuga.goto((580, -93))
tortuga.pendown()
tortuga.left(180)
tortuga.forward(65)